In [2]:
import pandas as pd

df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=["A","B","C"])

In [3]:
df.head() # Shows the first 5 rows of the dataframe

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [4]:
df.tail(2) # Shows the last 2 rows of the dataframe

   A  B  C
1  4  5  6
2  7  8  9

In [5]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes

# Loading Dataframes from files

In [8]:
coffee = pd.read_csv('./warmup-data/coffee.csv')
bios = pd.read_csv('./data/bios.csv')

# Accessing Data

In [46]:
coffee.sample(5) # Displays 5 random entries from the dataframe

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
13     Sunday       Latte          35
5   Wednesday       Latte          25
11   Saturday       Latte          35
8      Friday    Espresso          45

In [59]:
coffee.loc[:,["Day","Units Sold"]]

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [60]:
coffee.iloc[:,[0,1]]

          Day Coffee Type
0      Monday    Espresso
1      Monday       Latte
2     Tuesday    Espresso
3     Tuesday       Latte
4   Wednesday    Espresso
5   Wednesday       Latte
6    Thursday    Espresso
7    Thursday       Latte
8      Friday    Espresso
9      Friday       Latte
10   Saturday    Espresso
11   Saturday       Latte
12     Sunday    Espresso
13     Sunday       Latte